package me.bannock.virus;

import me.bannock.virus.utils.StartOnWindowsStartUtils;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.text.NumberFormatter;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputMethodEvent;
import java.awt.event.InputMethodListener;

public class VirusSetupForm {

    private final Config config;

    private JPanel form;
    private JButton startButton;
    private JButton setupToRunOnButton;
    private JRadioButton changeBackgroundRadioButton;
    private JRadioButton changeFolderIconsRadioButton;
    private JRadioButton imageFloodRadioButton;
    private JSpinner imageAmount;
    private JCheckBox scatterAcrossDriveCheckBox;
    private JRadioButton setUserIconRadioButton;
    private JRadioButton changePreLoginBackgroundRadioButton;
    private JRadioButton repeatHourlyRadioButton;

    /**
     * @param config The config object to link to this form
     */
    public VirusSetupForm(Config config) {
        this.config = config; // Set config

        // Make image amount field only accept numbers
        JFormattedTextField txt = ((JSpinner.NumberEditor) imageAmount.getEditor()).getTextField();
        ((NumberFormatter) txt.getFormatter()).setAllowsInvalid(false);

        // Set default value for image amount field
        imageAmount.setValue(config.getImageAmount());

        // Default config object linking listeners
        setUserIconRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                config.setSetUserIcon(setUserIconRadioButton.isSelected());
            }
        });
        imageFloodRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                config.setImageFlood(imageFloodRadioButton.isSelected());
                imageAmount.setEnabled(imageFloodRadioButton.isSelected());
                scatterAcrossDriveCheckBox.setEnabled(imageFloodRadioButton.isSelected());
            }
        });
        scatterAcrossDriveCheckBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                config.setScatterAcrossDrive(scatterAcrossDriveCheckBox.isSelected());
            }
        });
        imageAmount.addInputMethodListener(new InputMethodListener() {
            @Override
            public void inputMethodTextChanged(InputMethodEvent event) {
                config.setImageAmount(Integer.valueOf(imageAmount.getValue().toString()));
            }

            @Override
            public void caretPositionChanged(InputMethodEvent event) {
            }
        });
        changeFolderIconsRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                config.setChangeFolderIcons(changeFolderIconsRadioButton.isSelected());
            }
        });
        changeBackgroundRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                config.setChangeBackground(changeBackgroundRadioButton.isSelected());
            }
        });
        repeatHourlyRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                config.setRepeatHourly(repeatHourlyRadioButton.isSelected());
            }
        });
        changePreLoginBackgroundRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                config.setSetPreLoginBackground(changePreLoginBackgroundRadioButton.isSelected());
            }
        });
        setupToRunOnButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                StartOnWindowsStartUtils.setupJarRunningOnSystemStart("-autorun");
            }
        });
    }

    public JPanel getForm() {
        return form;
    }

    private void createUIComponents() {
        System.out.println("test");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        form = new JPanel();
        form.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(5, 5, 5, 5), -1, -1));
        form.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        startButton = new JButton();
        startButton.setText("Start");
        startButton.setToolTipText("Runs the virus and closes the ui");
        panel1.add(startButton, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        setupToRunOnButton = new JButton();
        setupToRunOnButton.setText("Setup to run on startup");
        setupToRunOnButton.setToolTipText("Sets the virus to run on startup with the currently entered config");
        panel1.add(setupToRunOnButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(7, 2, new Insets(5, 5, 5, 5), -1, -1));
        form.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        changeBackgroundRadioButton = new JRadioButton();
        changeBackgroundRadioButton.setEnabled(true);
        changeBackgroundRadioButton.setSelected(true);
        changeBackgroundRadioButton.setText("Change background");
        changeBackgroundRadioButton.setToolTipText("Changes the user's background");
        panel2.add(changeBackgroundRadioButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        changeFolderIconsRadioButton = new JRadioButton();
        changeFolderIconsRadioButton.setSelected(true);
        changeFolderIconsRadioButton.setText("Change folder icons");
        panel2.add(changeFolderIconsRadioButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        imageFloodRadioButton = new JRadioButton();
        imageFloodRadioButton.setSelected(true);
        imageFloodRadioButton.setText("Image flood");
        imageFloodRadioButton.putClientProperty("html.disable", Boolean.FALSE);
        panel2.add(imageFloodRadioButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        imageAmount = new JSpinner();
        imageAmount.setEnabled(true);
        imageAmount.setToolTipText("The amount of images to download");
        panel2.add(imageAmount, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scatterAcrossDriveCheckBox = new JCheckBox();
        scatterAcrossDriveCheckBox.setEnabled(true);
        scatterAcrossDriveCheckBox.setSelected(true);
        scatterAcrossDriveCheckBox.setText("Scatter across drive");
        scatterAcrossDriveCheckBox.setToolTipText("Scatter the image across the drive, makes it nearly impossible to remove them unless you use specialized tools");
        panel2.add(scatterAcrossDriveCheckBox, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        setUserIconRadioButton = new JRadioButton();
        setUserIconRadioButton.setSelected(true);
        setUserIconRadioButton.setText("Set user icon");
        setUserIconRadioButton.setToolTipText("Changes the user's profile icon");
        panel2.add(setUserIconRadioButton, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        changePreLoginBackgroundRadioButton = new JRadioButton();
        changePreLoginBackgroundRadioButton.setSelected(true);
        changePreLoginBackgroundRadioButton.setText("Change pre login background");
        changePreLoginBackgroundRadioButton.setToolTipText("Changes the background shown to the user on startup");
        panel2.add(changePreLoginBackgroundRadioButton, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        repeatHourlyRadioButton = new JRadioButton();
        repeatHourlyRadioButton.setSelected(true);
        repeatHourlyRadioButton.setText("Repeat hourly");
        repeatHourlyRadioButton.setToolTipText("Runs the virus hourly");
        panel2.add(repeatHourlyRadioButton, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return form;
    }
}
